ready
MargoVI/Spring_mvc_hiber_JPA_CRUD pull request #1
Opened 2024-01-28 15:24 UTC by IIMargo

2024-01-29 18:38 UTC, pdasilem requested changes

2024-01-29 18:38 UTC, pdasilem commented on src/main/java/web/services/UsersService.java
> +@Repository
это бизнес логика или репозиторий?

2024-01-29 19:06 UTC, IIMargo commented on src/main/java/web/services/UsersService.java
> +@Repository
залила изменения

2024-01-29 19:08 UTC, pdasilem requested changes

2024-01-29 19:08 UTC, pdasilem commented on src/main/java/web/dao/UserDao.java
> +@Transactional(readOnly = true)
здесь нружна эта транзакция?

2024-01-29 19:08 UTC, pdasilem commented on src/main/java/web/dao/UserDao.java
> +public class UserDao {
а где интерфейс/реализация?

2024-01-29 19:08 UTC, pdasilem commented on src/main/java/web/service/UserService.java
> +public class UserService {
аналогично - где реализация?

2024-01-29 19:21 UTC, IIMargo commented on src/main/java/web/service/UserService.java
> +public class UserService {
залила новые корректировки

2024-01-30 06:57 UTC, pdasilem requested changes

2024-01-30 06:57 UTC, pdasilem commented on src/main/java/web/service/UserServiceImpl.java
> +    private UserDaoImpl userDaoImpl;
видимо, еще не проснулись ))
внедрение только через интерфейсы. Дайте спрингу возможность проявить свои лучшие стороны )

2024-01-30 06:57 UTC, pdasilem commented on src/main/java/web/service/UserServiceImpl.java
> +@Transactional
Как правильно использовать аннотацию Транзакшнл?

2024-01-30 09:24 UTC, pdasilem approved these changes

2024-01-30 09:27 UTC, merged